<h1><font color='blue'> 8E and 8F: Finding the Probability P(Y==1|X)</font></h1>

<h2><font color='Geen'> 8E: Implementing Decision Function of SVM RBF Kernel</font></h2>

<font face=' Comic Sans MS' size=3>After we train a kernel SVM model, we will be getting support vectors and their corresponsing coefficients $\alpha_{i}$

Check the documentation for better understanding of these attributes: 

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
<img src='https://i.imgur.com/K11msU4.png' width=500>

As a part of this assignment you will be implementing the ```decision_function()``` of kernel SVM, here decision_function() means based on the value return by ```decision_function()``` model will classify the data point either as positive or negative

Ex 1: In logistic regression After traning the models with the optimal weights $w$ we get, we will find the value $\frac{1}{1+\exp(-(wx+b))}$, if this value comes out to be < 0.5 we will mark it as negative class, else its positive class

Ex 2: In Linear SVM After traning the models with the optimal weights $w$ we get, we will find the value of $sign(wx+b)$, if this value comes out to be -ve we will mark it as negative class, else its positive class.

Similarly in Kernel SVM After traning the models with the coefficients $\alpha_{i}$ we get, we will find the value of 
$sign(\sum_{i=1}^{n}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here $K(x_{i},x_{q})$ is the RBF kernel. If this value comes out to be -ve we will mark $x_{q}$ as negative class, else its positive class.

RBF kernel is defined as: $K(x_{i},x_{q})$ = $exp(-\gamma ||x_{i} - x_{q}||^2)$

For better understanding check this link: https://scikit-learn.org/stable/modules/svm.html#svm-mathematical-formulation
</font>

## Task E

> 1. Split the data into $X_{train}$(60), $X_{cv}$(20), $X_{test}$(20)

> 2. Train $SVC(gamma=0.001, C=100.)$ on the ($X_{train}$, $y_{train}$)

> 3. Get the decision boundry values $f_{cv}$ on the $X_{cv}$ data  i.e. ` `$f_{cv}$ ```= decision_function(```$X_{cv}$```)```  <font color='red'>you need to implement this decision_function()</font>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import numpy as np
from sklearn.svm import SVC

In [2]:
X, y = make_classification(n_samples=5000, n_features=5, n_redundant=0, n_classes=2, weights=[0.7], class_sep=0.7, random_state=15)
X

array([[-0.31030127, -1.47300088,  0.59124743,  0.8705559 , -0.42524742],
       [-0.17942473, -1.13412607, -0.14583869, -1.58198284, -1.32817149],
       [ 0.14981056,  0.77537917, -0.75092228,  0.31810543,  0.19646665],
       ...,
       [-1.09494183,  1.57206292,  1.09204273, -0.20535612,  0.00210579],
       [ 0.58144391, -0.16742201,  1.55598071,  0.82693028, -0.63111542],
       [-0.25435274,  0.10570486, -1.1573751 , -0.1002696 , -0.49148178]])

In [3]:
y

array([0, 0, 0, ..., 0, 0, 0])

### Pseudo code

clf = SVC(gamma=0.001, C=100.)<br>
clf.fit(Xtrain, ytrain)

<font color='green'>def</font> <font color='blue'>decision_function</font>(Xcv, ...): #use appropriate parameters <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>for</font> a data point $x_q$ <font color='green'>in</font> Xcv: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='grey'>#write code to implement $(\sum_{i=1}^{\text{all the support vectors}}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here the values $y_i$, $\alpha_{i}$, and $intercept$ can be obtained from the trained model</font><br>
   <font color='green'>return</font> <font color='grey'><i># the decision_function output for all the data points in the Xcv</i></font>
    
fcv = decision_function(Xcv, ...)  <i># based on your requirement you can pass any other parameters </i>

<b>Note</b>: Make sure the values you get as fcv, should be equal to outputs of clf.decision_function(Xcv)


In [4]:
# you can write your code here:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
X_train, X_cv, y_train, y_cv = train_test_split(X_train, y_train, test_size=0.25, stratify=y_train, random_state=42)

In [5]:
gamma = 0.001
C = 100

clf = SVC(gamma=0.001, C=100)
clf.fit(X_train, y_train)

def rbf(sv , xq , gamma):
  norm = np.linalg.norm(sv-xq) #Ref: https://numpy.org/doc/stable/reference/routines.linalg.html
  return  np.exp(-gamma *(norm**2))

def decision_function(X_cv, gamma, support_vectors, dual_coef, intercept):
  decision_vector = []
  for xq in X_cv :
    dec_func = 0
    for sv , dc  in zip(support_vectors , dual_coef[0]):
      dec_func += (dc * rbf(sv,xq, gamma))
    dec_func += intercept[0]
    decision_vector.append(dec_func)
  return decision_vector

#Ref: https://stackoverflow.com/questions/28503932/calculating-decision-function-of-svm-manually

support_vectors = clf.support_vectors_
dual_coef = clf.dual_coef_
intercept = clf.intercept_

f_cv = decision_function(X_cv, gamma, support_vectors, dual_coef, intercept)
f_cv

[-1.1070466710115792,
 -1.3698655183991573,
 -2.621525127743814,
 -0.8834677947079737,
 -1.7902659899562305,
 -1.561866521027758,
 -2.1008593582733166,
 2.4614628561514085,
 -3.994352517245394,
 0.008691986107246308,
 -1.5122917512961944,
 1.360186719340101,
 2.004211278305073,
 1.6697936923730285,
 -0.182400228879251,
 -2.782645763731244,
 1.6829142471188678,
 -2.559873414082622,
 1.6188810801060587,
 2.214984279444531,
 2.4318137193617364,
 -3.691925559552052,
 -1.6739997799548743,
 -2.910800735577686,
 -2.943710338189808,
 -0.22716126360290012,
 1.1013553844206943,
 2.059967514646525,
 -3.1726048535054954,
 2.150314995731202,
 -1.6253466317423086,
 2.1346548412529476,
 1.9635532120111439,
 -3.0442243381216,
 -4.4399136839345825,
 1.7857942930782347,
 -1.8175532897932296,
 -2.3666522215444754,
 -2.952228847475558,
 -3.9865124988377882,
 1.7886422512610185,
 -0.05207815617979428,
 1.9245653238564646,
 -2.9568111906321572,
 0.22937861023944528,
 -1.6671904937851618,
 -2.092638237431066

In [6]:
# The decision_function output for all the data points in the Xcv:
clf.decision_function(X_cv)

array([-1.10704667, -1.36986552, -2.62152513, -0.88346779, -1.79026599,
       -1.56186652, -2.10085936,  2.46146286, -3.99435252,  0.00869199,
       -1.51229175,  1.36018672,  2.00421128,  1.66979369, -0.18240023,
       -2.78264576,  1.68291425, -2.55987341,  1.61888108,  2.21498428,
        2.43181372, -3.69192556, -1.67399978, -2.91080074, -2.94371034,
       -0.22716126,  1.10135538,  2.05996751, -3.17260485,  2.150315  ,
       -1.62534663,  2.13465484,  1.96355321, -3.04422434, -4.43991368,
        1.78579429, -1.81755329, -2.36665222, -2.95222885, -3.9865125 ,
        1.78864225, -0.05207816,  1.92456532, -2.95681119,  0.22937861,
       -1.66719049, -2.09263824, -1.58935052, -2.03050157, -1.4382446 ,
       -4.09977722,  1.90186235, -0.33339212,  0.82164772, -0.41798351,
       -2.075796  , -0.31737241, -3.5189656 ,  2.01514927, -0.20706825,
       -0.62438203, -2.84854028,  0.08651498, -2.96396397, -2.11618303,
       -3.26861857, -2.50529939, -1.78360558, -0.2559236 , -1.36

<h2><font color='Geen'> 8F: Implementing Platt Scaling to find P(Y==1|X)</font></h2>

Check this <a href='https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a'>PDF</a>
<img src='https://i.imgur.com/CAMnVnh.png'>


## TASK F


> 4. Apply SGD algorithm with ($f_{cv}$, $y_{cv}$) and find the weight $W$ intercept $b$ ```Note: here our data is of one dimensional so we will have a one dimensional weight vector i.e W.shape (1,)``` 

> Note1: Don't forget to change the values of $y_{cv}$ as mentioned in the above image. you will calculate y+, y- based on data points in train data

> Note2: the Sklearn's SGD algorithm doesn't support the real valued outputs, you need to use the code that was done in the `'Logistic Regression with SGD and L2'` Assignment after modifying loss function, and use same parameters that used in that assignment.
<img src='https://i.imgur.com/zKYE9Oc.png'>
if Y[i] is 1, it will be replaced with y+ value else it will replaced with y- value

> 5. For a given data point from $X_{test}$, $P(Y=1|X) = \frac{1}{1+exp(-(W*f_{test}+ b))}$ where ` `$f_{test}$ ```= decision_function(```$X_{test}$```)```, W and b will be learned as metioned in the above step

__Note: in the above algorithm, the steps 2, 4 might need hyper parameter tuning, To reduce the complexity of the assignment we are excluding the hyerparameter tuning part, but intrested students can try that__


If any one wants to try other calibration algorithm istonic regression also please check these tutorials

1. http://fa.bianp.net/blog/tag/scikit-learn.html#fn:1

2. https://drive.google.com/open?id=1MzmA7QaP58RDzocB0RBmRiWfl7Co_VJ7

3. https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a

4. https://stat.fandom.com/wiki/Isotonic_regression#Pool_Adjacent_Violators_Algorithm


In [7]:
from sklearn.linear_model import SGDClassifier

In [8]:
N_positive = []
N_negative = []
for i in y_train:
    if i == 1:
        N_positive.append(i)
    else:
        N_negative.append(i)
        
N_positive = len(N_positive)
N_negative = len(N_negative)
N_positive, N_negative

(904, 2096)

In [9]:
y_positive = (N_positive + 1)/ (N_positive + 2)
y_positive

0.9988962472406181

In [10]:
y_negative = 1 / (N_negative + 2)
y_negative

0.00047664442326024784

In [11]:
new_y_cv = []

for j in y_cv:
  if j != 1:
    new_y_cv.append(y_negative)
  elif j == 1:
    new_y_cv.append(y_positive)
new_y_cv

[0.00047664442326024784,
 0.00047664442326024784,
 0.00047664442326024784,
 0.00047664442326024784,
 0.00047664442326024784,
 0.00047664442326024784,
 0.00047664442326024784,
 0.9988962472406181,
 0.00047664442326024784,
 0.9988962472406181,
 0.00047664442326024784,
 0.9988962472406181,
 0.9988962472406181,
 0.9988962472406181,
 0.00047664442326024784,
 0.00047664442326024784,
 0.9988962472406181,
 0.00047664442326024784,
 0.00047664442326024784,
 0.9988962472406181,
 0.9988962472406181,
 0.00047664442326024784,
 0.00047664442326024784,
 0.00047664442326024784,
 0.00047664442326024784,
 0.9988962472406181,
 0.9988962472406181,
 0.9988962472406181,
 0.00047664442326024784,
 0.9988962472406181,
 0.00047664442326024784,
 0.9988962472406181,
 0.9988962472406181,
 0.00047664442326024784,
 0.00047664442326024784,
 0.9988962472406181,
 0.00047664442326024784,
 0.00047664442326024784,
 0.00047664442326024784,
 0.00047664442326024784,
 0.9988962472406181,
 0.00047664442326024784,
 0.99889624724

In [12]:
%%time
from tqdm import tqdm
import math
from math import log

def initialize_weights(dim):
  dim = X_train[0]
  w = np.zeros((1,))
  b = 0
  return w,b

dim = X_train[0] 
w,b = initialize_weights(dim)

#1)sigmoid:
def sigmoid(z):
  return 1. / (1 + np. exp(-z))

#2)logloss:
def logloss(y_true,y_pred):
  loss = -sum(map(lambda y_true, y_pred: y_true*np.log10(y_pred) + (1-y_true)*np.log10(1-y_pred), y_true, y_pred))/len(y_true)
  return loss

#3)gradient_dw
def gradient_dw(x,y,w,b,alpha,N):
  dw = x * (y - sigmoid(np.dot(w, x) + b)) - (alpha / N) * w
  return dw

#4)gradient_db
def gradient_db(x,y,w,b):
  db = y - sigmoid(np.dot(w, x) + b)
  return db

#log loss:
log_loss=[]
epoch_list = []

def train(X_train,y_train):
  w,b = initialize_weights(X_train[0])
  eta0 = 0.0001
    
  for e in tqdm(range(epochs)):
    y_tr_pred=[]
    y_ts_pred=[]
    for p in range(len(X_train)):
      w = w + (eta0 * gradient_dw(X_train[p], y_train[p], w, b, alpha, N))
      b = b + (eta0 * gradient_db(X_train[p], y_train[p], w, b))

    for q in range(len(X_train)):
        z = np.dot(w,X_train[q])+b
        s = sigmoid(z)
        y_tr_pred.append(s)
    
    l_tr = logloss(y_train,y_tr_pred)
    log_loss.append(l_tr)
    epoch_list.append(e)
        
  return w,b

CPU times: user 2.63 ms, sys: 984 µs, total: 3.62 ms
Wall time: 3.63 ms


In [13]:
alpha=0.0001
eta0=0.0001
N=len(f_cv)
epochs=50
w,b = train(f_cv, new_y_cv)

100%|██████████| 50/50 [00:02<00:00, 20.12it/s]


In [14]:
w

array([1.20619531])

In [15]:
b

array([-0.15432535])

In [16]:
f_test = clf.decision_function(X_test)
f_test

array([-1.15155564e+00,  1.40151965e+00, -2.42750635e+00, -1.37157400e+00,
       -2.20530257e+00, -3.62017138e+00, -3.00033673e+00, -1.09157436e+00,
       -2.80838127e+00, -2.68359747e+00, -3.29284258e+00,  1.35947506e+00,
       -5.04237757e-01,  3.55883329e-01, -2.87801863e+00, -3.42962749e+00,
        4.79744439e-01,  1.84751873e+00, -3.25069644e+00, -3.41619331e+00,
       -1.67461845e-01, -2.16838148e+00,  1.71532833e+00, -1.54162035e+00,
       -3.09247385e+00, -3.33288587e+00, -2.07929057e+00, -3.44088633e+00,
        9.16739518e-01,  3.12724868e+00,  2.44702238e+00,  1.71762738e+00,
       -1.73462927e+00, -1.60687176e+00,  1.57267125e-01, -2.69638356e+00,
       -3.53502935e+00,  1.71835572e+00, -1.89451763e-01, -2.33824764e+00,
       -2.79698282e+00, -2.56284511e+00, -2.81185688e+00,  1.18258403e+00,
        5.46748827e-03, -1.26543313e+00, -3.80613896e+00, -3.22749386e+00,
       -2.05770093e+00, -3.49453367e+00, -2.84674355e+00, -4.12494719e+00,
        1.82180378e+00, -

In [17]:
p = 1 / 1 + np.exp(-((w*f_test)+b))
p

array([5.68013225e+00, 1.21520137e+00, 2.28100774e+01, 7.10257907e+00,
       1.76823449e+01, 9.29237190e+01, 4.45242147e+01, 5.35348742e+00,
       3.55283825e+01, 3.07035937e+01, 6.29381700e+01, 1.22639657e+00,
       3.14370270e+00, 1.75961812e+00, 3.85539263e+01, 7.40486716e+01,
       1.65420132e+00, 1.12566407e+00, 5.98681477e+01, 7.28745114e+01,
       2.42806023e+00, 1.69557126e+01, 1.14738668e+00, 8.49188615e+00,
       4.96403197e+01, 6.60032102e+01, 1.53300093e+01, 7.50474655e+01,
       1.38618392e+00, 1.02684308e+00, 1.06097682e+00, 1.14697853e+00,
       1.04557881e+01, 9.10536779e+00, 1.96524867e+00, 3.11652488e+01,
       8.39519217e+01, 1.14684946e+00, 2.46644511e+00, 2.05839174e+01,
       3.50569088e+01, 2.66775510e+01, 3.56734385e+01, 1.28024194e+00,
       2.15920044e+00, 6.36923187e+00, 1.16039128e+02, 5.82434552e+01,
       1.49616539e+01, 7.99974427e+01, 3.71636355e+01, 1.69986244e+02,
       1.12962290e+00, 3.99525216e+00, 4.71932437e+00, 2.05939748e+01,
      

#Thank you!